  version: 1.0.{build}
  configuration: Release
  platform: Any CPU
branches:
  only:
  - master
image: Previous Visual Studio 2017
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - davidrevoledo@d-genix.com
  subject: ServiceBus.LogginPlugin
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false