version: 1.0.{build}
branches:
  only:
  - master
image: Previous Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - davidrevoledo@d-genix.com
  subject: ServiceBus.LogginPlugin
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false